### ISSUE TITLE
some limit of storage in kubernetes

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [NIV-DEVELOPER/STO#4]
in [limit-storage-consumption](https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/)

we could see some limits of kubernetes for namespace, the count and sum storage quota:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storagequota
spec:
  hard:
    persistentvolumeclaims: "5"
    requests.storage: "5Gi"
```
